version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: qrex-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma # 프로젝트 폴더 내에 데이터 저장
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: always